---
abstract: 'We are CPAN authors'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors
no_index:
  directory:
    - t
    - inc
requires:
  CPAN::DistnameInfo: 0
  Carp: 0
  Class::Accessor::Fast: 0
  Exporter: 0
  File::Spec: 0
  IO::File: 0
  IO::Uncompress::Gunzip: 2.008
  JSON: 0
  LWP::UserAgent: 0
  Module::Find: 0
  Test::More: 0.47
  Test::UseAllModules: 0.09
  Try::Tiny: 0
  version: 0.74
version: 0.20
