--- #YAML:1.0
name:               Acme-CPANAuthors
version:            0.19
abstract:           We are CPAN authors
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Class::Accessor::Fast:  0
    CPAN::DistnameInfo:   0
    Exporter:             0
    File::Spec:           0
    Gravatar::URL:        0
    IO::File:             0
    IO::Uncompress::Gunzip:  2.008
    JSON:                 0
    LWP::UserAgent:       0
    Module::Find:         0
    Test::More:           0.47
    Test::UseAllModules:  0.09
    Try::Tiny:            0
    version:              0.74
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
